<?php

 $apiKey = "rzp_test_2chNaY7L7eS0qP";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="100" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Unlock all courses"
    data-name="E-Learning Website"
    data-description="Kickstart your Career!"
    data-image="https://icon2.cleanpng.com/20180304/ueq/kisspng-student-e-learning-distance-education-virtual-scho-tablet-pc-learning-network-course-5a9bb57dcd10b5.27200412152015398184.jpg"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
    <div id="frame" role="content"></div>
              <div class = "courses">
        <button type="button" onclick="location.href='loggedin.php';">Main Page</button>
      </div>
<style type="text/css">

                          button {
      width: 100%;
      padding: 10px;
      margin-top: 20px;
      border-radius: 20px;
      border: none;
      border-bottom: 4px solid rgba(100,150,150, 1);
      background: lightblue; 
      font-size: 16px;
      font-weight: 400;
      color: #000000;
      }
      button:hover {
      background: blue;
      color: #fff;
      }
          .courses{
      position:fixed;
      width: 15%;
      right:30px;
      top:1px;
      }
</style>


